name: Run Strategy

on:
  workflow_dispatch:

jobs:
  run-strategy:
    runs-on: ubuntu-latest
    environment: copilot
    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      RPC_FALLBACKS: ${{ secrets.RPC_FALLBACKS }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      VAULT_ADDRESS: ${{ secrets.VAULT_ADDRESS }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHATID: ${{ secrets.TELEGRAM_CHATID }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      
      # Protocol addresses (public)
      AAVE_POOL_ADDRESS_8453: ${{ vars.AAVE_POOL_ADDRESS_8453 || '0xA238Dd80C259a72e81d7e4664a9801593F98d1c5' }}
      AAVE_WETH_GATEWAY_8453: ${{ vars.AAVE_WETH_GATEWAY_8453 || '' }}
      AERODROME_ROUTER_8453: ${{ vars.AERODROME_ROUTER_8453 || '0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43' }}
      
      # Base chain token addresses (public addresses, can use vars with defaults)
      WETH_TOKEN_ADDRESS: ${{ vars.WETH_TOKEN_ADDRESS || '0x4200000000000000000000000000000000000006' }}
      USDC_BASE: ${{ vars.USDC_BASE || '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' }}
      USDBC_BASE: ${{ vars.USDBC_BASE || '0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA' }}
      USDT_BASE: ${{ vars.USDT_BASE || '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2' }}
      CBBTC_BASE: ${{ vars.CBBTC_BASE || '0xcbB7C0000aB88B473b1f5aFd9ef808440eed33Bf' }}
      CBETH_BASE: ${{ vars.CBETH_BASE || '0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22' }}
      WSTETH_BASE: ${{ vars.WSTETH_BASE || '0xc1CBa3fCea344f92D9239c08C0568f6F2F0ee452' }}
      
      # Beefy vault addresses
      BEEFY_USDC_CBBTC_VAULT: ${{ secrets.BEEFY_USDC_CBBTC_VAULT }}
      BEEFY_USDC_USDT_VAULT: ${{ secrets.BEEFY_USDC_USDT_VAULT }}
      BEEFY_WETH_USDC_VAULT: ${{ secrets.BEEFY_WETH_USDC_VAULT }}
      BEEFY_CBETH_WETH_VAULT: ${{ secrets.BEEFY_CBETH_WETH_VAULT }}
      BEEFY_WETH_USDT_VAULT: ${{ secrets.BEEFY_WETH_USDT_VAULT }}
      
      # ERC-4626 vault addresses
      STETH_YIELD_VAULT_BASE: ${{ vars.STETH_YIELD_VAULT_BASE || '' }}
      CBBTC_ERC4626_VAULT: ${{ vars.CBBTC_ERC4626_VAULT || '' }}
      USDC_ERC4626_VAULT: ${{ vars.USDC_ERC4626_VAULT || '0xef417a2512C5a41f69AE4e021648b69a7CdE5D03' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r bots/wave_rotation/requirements.txt

      - name: Run strategy
        run: python bots/wave_rotation/strategy.py
