name: Run Strategy

on:
  workflow_dispatch:

jobs:
  run-strategy:
    runs-on: ubuntu-latest
    environment: copilot
    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      RPC_FALLBACKS: ${{ secrets.RPC_FALLBACKS }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      VAULT_ADDRESS: ${{ secrets.VAULT_ADDRESS }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHATID: ${{ secrets.TELEGRAM_CHATID }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      
      # Protocol addresses
      AAVE_POOL_ADDRESS_8453: ${{ secrets.AAVE_POOL_ADDRESS_8453 }}
      AAVE_WETH_GATEWAY_8453: ${{ secrets.AAVE_WETH_GATEWAY_8453 }}
      AERODROME_ROUTER_8453: ${{ secrets.AERODROME_ROUTER_8453 }}
      
      # Base chain token addresses
      WETH_TOKEN_ADDRESS: ${{ secrets.WETH_TOKEN_ADDRESS }}
      USDC_BASE: ${{ secrets.USDC_BASE }}
      USDBC_BASE: ${{ secrets.USDBC_BASE }}
      USDT_BASE: ${{ secrets.USDT_BASE }}
      CBBTC_BASE: ${{ secrets.CBBTC_BASE }}
      CBETH_BASE: ${{ secrets.CBETH_BASE }}
      WSTETH_BASE: ${{ secrets.WSTETH_BASE }}
      
      # Beefy vault addresses
      BEEFY_USDC_CBBTC_VAULT: ${{ secrets.BEEFY_USDC_CBBTC_VAULT }}
      BEEFY_USDC_USDT_VAULT: ${{ secrets.BEEFY_USDC_USDT_VAULT }}
      BEEFY_WETH_USDC_VAULT: ${{ secrets.BEEFY_WETH_USDC_VAULT }}
      BEEFY_CBETH_WETH_VAULT: ${{ secrets.BEEFY_CBETH_WETH_VAULT }}
      BEEFY_WETH_USDT_VAULT: ${{ secrets.BEEFY_WETH_USDT_VAULT }}
      
      # ERC-4626 vault addresses
      STETH_YIELD_VAULT_BASE: ${{ secrets.STETH_YIELD_VAULT_BASE }}
      CBBTC_ERC4626_VAULT: ${{ secrets.CBBTC_ERC4626_VAULT }}
      USDC_ERC4626_VAULT: ${{ secrets.USDC_ERC4626_VAULT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r bots/wave_rotation/requirements.txt

      - name: Run strategy
        run: python bots/wave_rotation/strategy.py
